name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  NODE_VERSION: '21'
  BUILD_VERSION: 'v0.7.1'

jobs:
  deps:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.3.0
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '${{ env.NODE_VERSION }}'
          cache: 'pnpm'
      - name: Deps
        run: scripts/deps
        env:
          LOCK: true
      - name: Archive Modules
        timeout-minutes: 5
        uses: actions/cache/save@v4
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: |
            ${{ github.workspace }}/node_modules

  build:
    needs:
      - deps
    if: github.event_name == 'pull_request'
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Unarchive Node Modules
        timeout-minutes: 5
        uses: actions/cache/restore@v4
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: |
            ${{ github.workspace }}/node_modules
      - name: Build
        run: scripts/build

  build-publish:
    needs:
      - deps
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Unarchive Node Modules
        timeout-minutes: 5
        uses: actions/cache/restore@v4
        with:
          key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
          path: |
            ${{ github.workspace }}/node_modules
      - name: Build
        run: scripts/build
      - name: Package
        run: scripts/package
        env:
          VERSION: '${{ env.BUILD_VERSION }}'
      - name: Setup MinIO Client
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv mc /usr/local/bin/
      - name: Upload to S3
        run: |
          mc alias set s3 --api=S3v4 https://cache.ali.wodcloud.com ${{ secrets.S3_ACCESS_KEY_ALIYUN }} ${{ secrets.S3_SECRET_KEY_ALIYUN }}
          mc cp dist/${{ env.BUILD_VERSION }}.tar.gz s3/vscode/gpustack/gpustack-ui-${{ env.BUILD_VERSION }}.tar.gz
          mc cp dist/${{ env.BUILD_VERSION }}.tar.gz s3/vscode/gpustack/gpustack-ui-latest.tar.gz
        env:
          S3_ACCESS_KEY_ALIYUN: ${{ secrets.S3_ACCESS_KEY_ALIYUN }}
          S3_SECRET_KEY_ALIYUN: ${{ secrets.S3_SECRET_KEY_ALIYUN }}
