name: CI

on:
  push:
    branches:
      - 'main'

env:
  BUILD_VERSION: 'v0.7.6'

jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 1
          persist-credentials: false
      - name: Setup Pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.31.0
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Deps
        run: scripts/deps
        env:
          LOCK: true
      - name: Build
        run: scripts/build
      - name: Package
        run: scripts/package
        env:
          VERSION: '${{ env.BUILD_VERSION }}'
      - name: Setup MinIO Client
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          sudo mv mc /usr/local/bin/
      - name: Upload to S3
        run: |
          mc alias set s3 --api=S3v4 https://cache.ali.wodcloud.com ${{ secrets.S3_ACCESS_KEY_ALIYUN }} ${{ secrets.S3_SECRET_KEY_ALIYUN }}
          mc cp dist/${{ env.BUILD_VERSION }}.tar.gz s3/vscode/gpustack/gpustack-ui-${{ env.BUILD_VERSION }}.tar.gz
          mc cp dist/${{ env.BUILD_VERSION }}.tar.gz s3/vscode/gpustack/gpustack-ui-latest.tar.gz
        env:
          S3_ACCESS_KEY_ALIYUN: ${{ secrets.S3_ACCESS_KEY_ALIYUN }}
          S3_SECRET_KEY_ALIYUN: ${{ secrets.S3_SECRET_KEY_ALIYUN }}
